"""firts db

Revision ID: ae4b7210a263
Revises: 
Create Date: 2024-03-31 10:13:02.250764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae4b7210a263'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oficina',
    sa.Column('Cod_Ofi', sa.String(length=5), nullable=False),
    sa.Column('NOMBRE', sa.String(length=100), nullable=True),
    sa.Column('DESCRIPCION', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('Cod_Ofi')
    )
    with op.batch_alter_table('oficina', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_oficina_NOMBRE'), ['NOMBRE'], unique=True)

    op.create_table('perfil',
    sa.Column('Idnivel', sa.Integer(), nullable=False),
    sa.Column('DENOMINACION', sa.String(length=60), nullable=True),
    sa.Column('DESCRIPCION', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('Idnivel'),
    sa.UniqueConstraint('DENOMINACION')
    )
    op.create_table('regimen',
    sa.Column('IdRegimen', sa.Integer(), nullable=False),
    sa.Column('DENOMINACION', sa.String(length=50), nullable=True),
    sa.Column('HORASMENSUALES', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('IdRegimen'),
    sa.UniqueConstraint('DENOMINACION')
    )
    op.create_table('turno',
    sa.Column('IdTurno', sa.Integer(), nullable=False),
    sa.Column('NOMBRE', sa.String(length=20), nullable=True),
    sa.Column('CODIGO', sa.String(length=5), nullable=True),
    sa.Column('HORAS', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('IdTurno'),
    sa.UniqueConstraint('CODIGO'),
    sa.UniqueConstraint('NOMBRE')
    )
    op.create_table('asignacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('menu', sa.String(length=100), nullable=True),
    sa.Column('Idnivel', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Idnivel'], ['perfil.Idnivel'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gerarquia',
    sa.Column('Id_Gerar', sa.Integer(), nullable=False),
    sa.Column('Cod_Ofi_Ante', sa.String(length=5), nullable=True),
    sa.Column('Cod_Ofi', sa.String(length=5), nullable=True),
    sa.ForeignKeyConstraint(['Cod_Ofi'], ['oficina.Cod_Ofi'], ),
    sa.PrimaryKeyConstraint('Id_Gerar')
    )
    op.create_table('persona',
    sa.Column('DNI', sa.String(length=11), nullable=False),
    sa.Column('NOMBRE', sa.String(length=50), nullable=True),
    sa.Column('APELLIDO_PATERNO', sa.String(length=100), nullable=True),
    sa.Column('APELLIDO_MATERNO', sa.String(length=100), nullable=True),
    sa.Column('FECHA_NAC', sa.Date(), nullable=True),
    sa.Column('EMAIL', sa.String(length=100), nullable=True),
    sa.Column('TELEFONO', sa.String(length=9), nullable=True),
    sa.Column('DIRECCION', sa.String(length=100), nullable=True),
    sa.Column('Cod_Ofi', sa.String(length=5), nullable=True),
    sa.ForeignKeyConstraint(['Cod_Ofi'], ['oficina.Cod_Ofi'], ),
    sa.PrimaryKeyConstraint('DNI'),
    sa.UniqueConstraint('EMAIL')
    )
    with op.batch_alter_table('persona', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_persona_DNI'), ['DNI'], unique=False)

    op.create_table('perregimen',
    sa.Column('IdRegPer', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('DNI', sa.String(length=11), nullable=True),
    sa.Column('IdRegimen', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['DNI'], ['persona.DNI'], ),
    sa.ForeignKeyConstraint(['IdRegimen'], ['regimen.IdRegimen'], ),
    sa.PrimaryKeyConstraint('IdRegPer')
    )
    op.create_table('usuario',
    sa.Column('DNI', sa.String(length=11), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=True),
    sa.Column('Idnivel', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['DNI'], ['persona.DNI'], ),
    sa.ForeignKeyConstraint(['Idnivel'], ['perfil.Idnivel'], ),
    sa.PrimaryKeyConstraint('DNI')
    )
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuario_username'), ['username'], unique=True)

    op.create_table('programacion',
    sa.Column('IdProgramacion', sa.Integer(), nullable=False),
    sa.Column('FECHAI', sa.DateTime(), nullable=True),
    sa.Column('FECHAF', sa.DateTime(), nullable=True),
    sa.Column('IdRegPer', sa.Integer(), nullable=True),
    sa.Column('IdTurno', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['IdRegPer'], ['perregimen.IdRegPer'], ),
    sa.ForeignKeyConstraint(['IdTurno'], ['turno.IdTurno'], ),
    sa.PrimaryKeyConstraint('IdProgramacion')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('programacion')
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuario_username'))

    op.drop_table('usuario')
    op.drop_table('perregimen')
    with op.batch_alter_table('persona', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_persona_DNI'))

    op.drop_table('persona')
    op.drop_table('gerarquia')
    op.drop_table('asignacion')
    op.drop_table('turno')
    op.drop_table('regimen')
    op.drop_table('perfil')
    with op.batch_alter_table('oficina', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_oficina_NOMBRE'))

    op.drop_table('oficina')
    # ### end Alembic commands ###
